# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarQ'
    organization: 'birdmodify69'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=birdmodify69_spring-boot-demo
      sonar.branch.name=develop




- script: |
    echo Starting the build
    mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=birdmodify69_spring-boot-demo
  displayName: 'Test Script with Maven'



- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'



    
